apiVersion: v1
kind: Service
metadata:
  labels:
    name: spring-petclinic
  name: spring-petclinic
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: spring-petclinic
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: spring-petclinic
        image: DOCKERHUB_USER/spring-petclinic
        ports:
        - containerPort: 8080